### ISSUE TITLE
Zitadel for Bun?

### ISSUE THREAD

**Issue by redbar0n** [smartive/zitadel-node#325]
Any plans to release a similar library that would allow using Zitadel with Bun?

**Comment by redbar0n** [comment]
@buehler @eliobischof

**Comment by buehler** [comment]
Hey @redbar0n 
Since bun claims to be compatible with node/esm/cjs, it is unlikely that we will provide special support for bun. Further because it's pretty fresh in 1.0. I don't know, which packages are compatible and which are not.
