### ISSUE TITLE
The types are now broken

### ISSUE THREAD

**Issue by notmedia** [smartive/zitadel-node#372]
Since new major release the types are broken. Try to install this package in separate project.

**Comment by notmedia** [comment]
@buehler @eliobischof please, look at this issue

**Comment by LonguCodes** [comment]
`Cannot find module '@zitadel/node/credentials' or its corresponding type declarations`

Types work if using whole path `@zitadel/node/dist/esm/credentials`, but since this path is not in `exports`, node does not want to work with that

**Comment by notmedia** [comment]
Yes, but this a hack. IMO this is not good.

And if you look in the package.json how tshy build distribution the exports are set, but exports.types can work only if module resolution is set to Node16 or NodeNext in tsconfig.

**Comment by notmedia** [comment]
Also I think that we can use one declaration file for both esm and cjs

**Comment by notmedia** [comment]
For example this could be fixed by adding to `package.json`, but all types should be moved to the root of distribution.

```json
"typesVersions": {
    "*": {
      "api": [
        "dist/commonjs/api/index.d.ts"
      ],
      "credentials": [
        "dist/commonjs/credentials/index.d.ts"
      ]
    }
},
  ```

**Comment by buehler** [comment]
It was my first experience with tshy to be honest.

What should be written into the package json to allow this kind of setup? The distinction of the apis is quite nice at the moment. I don't know if I would want to merge everything together again.

**Comment by buehler** [comment]
Ah I see. When adding 
```
"typesVersions": {
    "*": {
      "api": [
        "dist/commonjs/api/index.d.ts"
      ],
      "credentials": [
        "dist/commonjs/credentials/index.d.ts"
      ]
    }
},
```

It does work. I'll have a look.
