### ISSUE TITLE
Difficult/impossible to use much/most of the types

### ISSUE THREAD

**Issue by wlinna** [smartive/zitadel-node#393]
I am trying to use `addHumanUser` by creating a client with `createManagementClient`. However, 

```
import { createAccessTokenInterceptor, createManagementClient, } from '@zitadel/node/api';

const client = createManagementClient(zitadelUrl, createAccessTokenInterceptor(...));
```

However, assigning gender seems difficult, because it appears I cannot import Gender etc. I can't import `AddHumanUserRequest`, so I can't just use `AddHumanUserRequest.fromJson` and the string values specified in [Zitadel documentation](https://zitadel.com/docs/apis/resources/mgmt/management-service-import-human-user) either

I noticed an [issue](https://github.com/smartive/zitadel-node/issues/372) that seemed related, but it was marked as solved.

I use version 2.0.8 of zitadel-node with TypeScript

**Comment by buehler** [comment]
hey @wlinna 
I'll have a look at the types again :)

**Comment by hisabimbola** [comment]
Yeah, I'm having same issue. not possible to use in internal imports

**Comment by Nactik** [comment]
Hey !
I'm having the same issue here. This package is hard to use when using a `bundler` as `moduleResolution` since the types are not exported :(
